App/urls.py
from django.conf.urls import include, url
# from .views import checkMachineAPI, createMachineAPI, main, test
from .views import *
from django.urls import path

app_name = "API"

urlpatterns = [
    url(r'^$', main, name='main'),
    path('check/machine', checkMachineAPI, name="check_machine"),
    path('create/machine', createMachineAPI, name="create_machine"),
    url(r'^test/$', test, name="test"),
    url(r'^detail/(?P<pk>\d+)/$', detail, name="detail"),
    url(r'^category/$', category, name="category"),        
    url(r'^g_category/$', g_category, name="g_category"),
    url(r'^r_category/$', r_category, name="r_category"),
    url(r'^b_category/$', b_category, name="b_category"),
    url(r'^f_category/$', f_category, name="f_category"),
    url(r'^write/$', write, name="write")
]

daedong/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

#이미지
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('App.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/models.py
from django.db import models

class MachineID(models.Model):
    uuid = models.CharField(max_length=255, verbose_name="고유ID", unique=True)
    nickname = models.CharField(max_length=32, verbose_name="닉네임")

    def __str__(self):
        return str(self.nickname)

class Store(models.Model):
    photo = models.ImageField(upload_to='%Y/%m/%d/orig')
    store_name = models.CharField(max_length=255)
    menu = models.TextField(max_length=200)
    tel = models.CharField(max_length=255)
    time = models.TextField(max_length=255)
    day = models.CharField(max_length=255, blank=True)
    park = models.CharField(max_length=200, blank=True)
    address = models.CharField(max_length=255)
    tag = models.CharField(max_length=222)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.store_name)

App/forms.py
from django import forms
from .models import Store, MachineID

class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = ('photo', 'store_name', 'menu', 'tel', 'time', 'day', 'park', 'address', 'tag')

#     def __init__(self, *args, **kwargs):
# #         super(PostForm, self).__init__(*args, **kwargs)
# #         self.fields['photo'].required = False #유효성 검사 패스

App/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.http import require_http_methods
from .models import *
import json
from .forms import StoreForm

def main(request):
    # post = MachineID.objects.all()
    return render(request, 'main.html', {})

# Json Context 출력
def Result(status, msg, data=None):
    result = {}
    result['status'] = status
    result['message'] = msg
    result['data'] = data
    return result

@require_http_methods(["POST"])
def checkMachineAPI(request):
    # MachineID 가져오기
    machineID = request.POST.get('machineID', None)

    # MachineID 존재 여부 확인
    try:
        user = MachineID.objects.get(uuid=machineID)
        context = Result("success", user.nickname +"님, 환영합니다.")
    except:
        context = Result("error", "처음 접속 유저입니다.")

    return HttpResponse(json.dumps(context), content_type="application/json")


@require_http_methods(["POST"])
def createMachineAPI(request):
    # MachineID 가져오기
    machineID = request.POST.get('machineID', None)
    nickname = request.POST.get('nickname', None)
    # MachineID 존재 여부 확인
    
    try:
        # print(machineID)
        # print(nickname)
        user = MachineID.objects.create(uuid=machineID, nickname=nickname)
        print(user)
        context = Result("success", user.nickname +"님, 환영합니다.")
    except:
        context = Result("error", "이미 존재하는 uuid 입니다.")

    return HttpResponse(json.dumps(context), content_type="application/json")


def test(request):
    testform = StoreForm()
    print(request.POST["menu"])
    return render(request, 'a.html', {'testform': testform})

def detail(request, pk):
    post = Store.objects.get(pk=pk)
    return render(request, 'detail.html', {'s_post':post})

def category(request):
    post = Store.objects.all()
    return render(request, 'category.html', {'form': post})

def g_category(request):
    gun_post = Store.objects.filter(tag='사격')
    return render(request, 'category.html', {'form': gun_post})

def r_category(request):
    room_post = Store.objects.filter(tag='방탈출')
    return render(request, 'category.html', {'form': room_post})

def f_category(request):
    fish_post = Store.objects.filter(tag='낚시')
    return render(request, 'category.html', {'form': fish_post})

def b_category(request):
    break_post = Store.objects.filter(tag='레이지룸')
    return render(request, 'category.html', {'form': break_post})

def write(request):
    if request.method == 'POST':
        w_form = StoreForm(request.POST, request.FILES)

        if w_form.is_valid():
            post = w_form.save(commit = False)
        # Post.objects.create(title=request.POST['post_title_text'], content=request.POST.get('fields', ''))
            post.save()
            return redirect('API:category')
    else:
        w_form = StoreForm()
        return render(request, 'review.html', {'w_form':w_form})

App/templates/MainPage.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<p style="margin-top:-12px">
    <b>Chrome 브라우저는 https 환경에서만 geolocation을 지원합니다.</b> 참고해주세요.
</p>
<div id="map" style="width:100%;height:350px;"></div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=e5827c3590ec63beb093418d8c26b83a"></script>
<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = { 
        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨 
    }; 

var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

// HTML5의 geolocation으로 사용할 수 있는지 확인합니다 
if (navigator.geolocation) {
    
    // GeoLocation을 이용해서 접속 위치를 얻어옵니다
    navigator.geolocation.getCurrentPosition(function(position) {
        
        var lat = position.coords.latitude, // 위도
            lon = position.coords.longitude; // 경도
        
        var locPosition = new kakao.maps.LatLng(lat, lon), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
            message = '<div style="padding:5px;">여기에 계신가요?!</div>'; // 인포윈도우에 표시될 내용입니다
        
        // 마커와 인포윈도우를 표시합니다
        displayMarker(locPosition, message);
            
      });
    
} else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다
    
    var locPosition = new kakao.maps.LatLng(33.450701, 126.570667),    
        message = 'geolocation을 사용할수 없어요..'
        
    displayMarker(locPosition, message);
}

// 지도에 마커와 인포윈도우를 표시하는 함수입니다
function displayMarker(locPosition, message) {

    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({  
        map: map, 
        position: locPosition
    }); 
    
    var iwContent = message, // 인포윈도우에 표시할 내용
        iwRemoveable = true;

    // 인포윈도우를 생성합니다
    var infowindow = new kakao.maps.InfoWindow({
        content : iwContent,
        removable : iwRemoveable
    });
    
    // 인포윈도우를 마커위에 표시합니다 
    infowindow.open(map, marker);
    
    // 지도 중심좌표를 접속위치로 변경합니다
    map.setCenter(locPosition);      
}    
</script>
{% endblock %}

App/templates/a.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form method="POST" action="API:test">
        <button type="submit" name="menu" >칵테일</button>
    </form>
</body>
</html>

App/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% block stylesheet %}{% endblock %}">
	<link rel="stylesheet" href="{% static 'css/topbar.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 팝업라이브러리 -->
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <!-- jQuery 라이브러리 -->
    <script 
    src="https://code.jquery.com/jquery-3.3.1.js"
  	integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  	crossorigin="anonymous"></script>
	<!-- 구글 애드센스 -->
	<meta name="google-site-verification" content="JxQy7UNZxOwrkiJD-k0Chv80JIVm79ttXe3tFtYsXv0" />
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<script>
	  (adsbygoogle = window.adsbygoogle || []).push({
	    google_ad_client: "ca-pub-5552721723401332",
	    enable_page_level_ads: true
	  });
	</script>
	<!-- 폰트 -->
	{% comment %} <link href="https://fonts.googleapis.com/css?family=East+Sea+Dokdo" rel="stylesheet"> {% endcomment %}
	<!-- Device-UUID -->
	<script src="{% static 'device-uuid.js' %}"></script>
</head>
<body style="margin: 0px">
<style>
	html, body, input, button{
		font-family: 'East Sea Dokdo', cursive;
	}
	.swal-footer{
		text-align: center;
	}
	.swal-button{
		background-color: rgb(16, 56, 148);
	}
	.swal-title{
		font-size: 30px;
	}
	.swal-text{
		font-size: 25px;
	}
	.swal-button{
		font-size: 20px;
	}
</style>
{% block content %}

{% endblock content %}
<!-- Machin ID를 이용해 계정 확인 -->
<script>
var uuid = new DeviceUUID().get()

// 새로운 기계 접속 시 유저 생성하기
createUser = function(){
	swal({
        title: "반갑습니다!",
        text: "닉네임을 적어주세요.",
        content: "input",
        button: "확인",
    })
    .then(name => {
	  	if (!name) throw null
	 
	  	console.log(name)
		$.ajax({ 
		    type: "POST", 
		    url: "{% url 'API:create_machine' %}",
		    data: {
		        'machineID': uuid,
		        'nickname': name,
		        'csrfmiddlewaretoken': '{{ csrf_token }}'
		    },
		    dataType: "json", 
		    success: function(response){
		        console.log(response)
		        if (response.status=='success'){
		            location.reload()
		        }
		        else{
		            swal({
			            title: response.message,
			            button: "확인",
			        });
		        }
		    },
		    error: function(request, status, error){
		    },
		});
	})
	.catch(err => {
	 	if (err) {
	    	swal("에러메세지", "The AJAX request failed!", "확인")
	  	} else {
	    	swal.stopLoading()
	    	swal.close()
	  	}
	});
}

// 페이지 로드 시 환영 메세지 or 유저 생성
$(document).ready(function(){

	$.ajax({ 
	    type: "POST", 
	    url: "{% url 'API:check_machine' %}",
	    data: {
	        'machineID': uuid,
	        'csrfmiddlewaretoken': '{{ csrf_token }}'
	    },
	    dataType: "json", 
	    success: function(response){
	        console.log(response)
	        if (response.status=='error'){
	            createUser()
	        }
	        else{
	            swal({
		            title: response.message,
		            button: "확인",
		        });
	        }
	    },
	    error: function(request, status, error){
	    },
	});
})
</script>
</body>
</html>

App/templates/category.html
{% extends 'm_base.html' %}
{% load static %}
{% block stylesheet %}{% static 'css/category.css' %}{% endblock %}
{% block title %}이색기{% endblock  %}

{% block content %}
<body>
    <header>
        <div class="bar_title">
            <a href="{% url 'API:main' %}"><img src="{% static 'img/title.png' %}" alt=""></a>
        </div>
        <div class="topbar">
            <a href="{% url 'API:main' %}"><img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="rightmenu">
             <a href="#" class="searchb"><img src="{% static 'img/search.png' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/menu.png' %}" alt=""></a>
        </div>
        </div>
    </header>
    <div class="searchbox hide">
        <div class="searchbar">
            <input type="text" placeholder="검색어를 입력하세요.">
            <a href=""><img src="{% static 'img/search.png' %}" alt=""></a>
        </div>
        <div class="shadow"></div>
    </div>

    <nav>
        <div class="arrow"></div>
        <ul class="category">
            <li><a href="{% url 'API:g_category' %}">사격</a></li>
            <li><a href="{% url 'API:f_category' %}">낚시</a></li>
            <li><a href="{% url 'API:r_category' %}">방탈출</a></li>
            <li><a href="{% url 'API:b_category' %}">레이지룸</a></li>
            <li><a href="">안티</a></li>
            <li><a href="">양궁</a></li>
        </ul>
        <div class="arrow nag"></div>
    </nav>

    <section>
        <ul class="category_list">
        {% for posts in form %}
            <li>
                <a href="{% url 'API:detail' pk=posts.pk  %}">
                    <img class="back" src="{{posts.photo.url}}" alt="">
                    <h4>{{posts.store_name}}</h4>
                    {% comment %} <p>아주 좋은 카페</p> {% endcomment %}
                    <hr>
                    <p>{{posts.address}}</p>
                </a>
                <img class="heart" src="{% static 'img/heart.png' %}" alt="">
            </li>
        {% endfor %}
        </ul>
        
    </section>




    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script>
        $('.category li').each(function(index, item){
            $(item).css('left',""+index*80+"px");
            console.log("'"+index*30+"px'"+"100px");
        })

        $( document ).ready(function() { 
            $('.searchb').click(function(){
                $('.searchbox').removeClass('hide')
            })
            $('.shadow').click(function(){
                $('.searchbox').addClass('hide')
            })
            $('.heart').click(function(){
                $(this).attr('src', '{% static 'img/ha.png' %}').removeClass('heart').addClass('ha');
            })
            $('.ha').click(function(){
                $(this).attr('src', '{% static 'img/heart.png' %}').removeClass('ha').addClass('heart');
            })

        });
    </script>
</body>
{% endblock %}

App/templates/detail.html
{% extends 'm_base.html' %}
{% load static %}
    {% block stylesheet %}{% static 'css/detail.css' %}{% endblock %}
    {% block title %}이색기{% endblock  %}

{% block content %}
    <header>
        <div class="bar_title">{{s_post.store_name}}</div>
        <div class="topbar">
            <a href="{% url 'API:category' %}"><img src="{% static 'img/arrow.png' %}" alt=""></a>
            <div class="rightmenu">
                <a href="#" class="searchb"><img src="{% static 'img/search.png' %}" alt=""></a>
                <a href="#"><img src="{% static 'img/menu.png' %}" alt=""></a>
            </div>
        </div>
    </header>
    <div class="searchbox hide">
        <div class="searchbar">
            <input type="text" placeholder="검색어를 입력하세요.">
            <a href=""><img src="{% static 'img/search.png' %}" alt=""></a>
        </div>
        <div class="shadow"></div>
    </div>

    <div class="titleimg">
        <img src="{{s_post.photo.url}}" alt="">
    </div>

    <section>
        <nav>
            <ul class="navbar">
                <li>
                    <button class="point b 1">정보</button>
                </li>
                <li>
                    <button class="b 2">리뷰</button>
                </li>
            </ul>
        </nav>
        <div class="contents">
        {% comment %} {% for s in s_post %} {% endcomment %}
            {% comment %} <p><span>매장소개</span><br>반짝반짝</p> {% endcomment %}
            <span>전화번호</span><p>{{s_post.tel}}</p>
            <span>영업시간</span><p>{{s_post.time}}</p>
            <span>휴무</span><p>{{s_post.day}}</p>
            <span>주차</span><p>{{s_post.park}}</p>
            <span>주소</span><p>{{s_post.address}}</p>
        {% comment %} {% endfor %} {% endcomment %}
            <div id="map"></div>
        </div>

        <div class="review hide">
            <div class="write">
                <a href="">글쓰기</a>
            </div>
            <ul class="R_ul">
                <li>
                    <div class="R_ul_box">
                        <p class="name">송태현</p>
                        <p class="day">2019-07-26</p>
                    </div>
                    <hr>
                    <p class="con">정말로 맛있었습니다. gkgkgkgkgkgkgk</p>
                </li>
                <li>
                    <p class="name">송태현</p>
                    <p class="day">2019-07-26</p>
                    <hr>
                    <p class="con">정말로 맛있었습니다.</p>
                </li>
            </ul>
        </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script>
        $( document ).ready(function() {
            $('.1').click(function(){
                $('.contents').removeClass('hide');
                $('.review').addClass('hide');
                $('.2').removeClass('point');
                $(this).addClass('point');
            })
            $('.2').click(function(){
                $('.contents').addClass('hide');
                $('.review').removeClass('hide');
                $('.1').removeClass('point');
                $(this).addClass('point');
            })
            $('.searchb').click(function(){
                $('.searchbox').removeClass('hide')
            })
            $('.shadow').click(function(){
                $('.searchbox').addClass('hide')
            })
        });
    </script>



    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=e5827c3590ec63beb093418d8c26b83a"></script>
	<script>
		var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
        mapOption = { 
            center: new kakao.maps.LatLng(37.5511391, 126.92224770000007), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨
        };

        var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

        // 마커가 표시될 위치입니다 
        var markerPosition  = new kakao.maps.LatLng(37.5511391, 126.92224770000007); 

        // 마커를 생성합니다
        var marker = new kakao.maps.Marker({
            position: markerPosition
        });

        // 마커가 지도 위에 표시되도록 설정합니다
        marker.setMap(map);
        
	</script>
{% endblock %}

App/templates/m_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta charset="utf-8">
    {% block linkstyle %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/topbar.css' %}">
    <link rel="stylesheet" href="{% block stylesheet %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    {% block script %}{% endblock %}
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

App/templates/main.html
{% extends "base.html" %}
{% load static %}
{% block stylesheet %}{% static 'css/main.css' %}{% endblock %}
{% block title %}이색기{% endblock  %}

{% block content %}
    <header>
        <div class="bar_title">
            <a href=""><img src="{% static 'img/title.png' %}" alt=""></a>
        </div>
        <div class="topbar">
            <a href=""><img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="rightmenu">
             <a href="#" class="searchb"><img src="{% static 'img/search.png' %}" alt=""></a>
            <a href="#" class="menub"><img src="{% static 'img/menu.png' %}" alt=""></a>
        </div>
        </div>
    </header>
    <div class="searchbox hide">
        <div class="searchbar">
            <input type="text" placeholder="검색어를 입력하세요.">
            <a href=""><img src="{% static 'img/search.png' %}" alt=""></a>
        </div>
        <div class="shadow"></div>
    </div>
    
    <div class="main">
        <div class="mainimg"></div>
        <div class="maintext">
            <p>이색 카페 찾으러 가기</p>
            <a href="{% url 'API:category' %}">카테고리 검색</a>
        </div>
    </div>

    <div class="review">
        <div class="reviewimg"></div>
        <div class="reviewtext">
            <p>이색 카페 등록하기</p>
            <a href="{% url 'API:write' %}">카페 등록하기</a>
        </div>
    </div>
{% endblock %}

App/templates/review.html
{% extends 'm_base.html' %}
{% load static %}
{% block stylesheet %}{% static 'css/review.css' %}{% endblock %}
{% block title %}이색기{% endblock  %}

{% block content %}
    <header>
        <div class="bar_title">
            <a href=""><img src="{% static 'img/title.png' %}" alt=""></a>
        </div>
        <div class="topbar">
            <a href=""><img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="rightmenu">
             <a href="#" class="searchb"><img src="{% static 'img/search.png' %}" alt=""></a>
            <a href="#" class="menub"><img src="{% static 'img/menu.png' %}" alt=""></a>
        </div>
        </div>
    </header>
    <div class="searchbox hide">
        <div class="searchbar">
            <input type="text" placeholder="검색어를 입력하세요.">
            <a href=""><img src="{% static 'img/search.png' %}" alt=""></a>
        </div>
        <div class="shadow"></div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        <h3 class="title_form">이색 카페 등록하기</h3>
        <div class="text">
            {% csrf_token %}
            <div class="file">
                <input type="file" name="photo">
            </div>
            <input type="text" placeholder="매장이름" name="store_name">
            <textarea name="menu" cols="30" rows="10" placeholder="메뉴"></textarea>
            <input type="text" placeholder="번호" name="tel">
            <textarea name="time" cols="30" rows="10" placeholder="영업시간"></textarea>
            <input type="text" placeholder="휴일" name="day">
            <input type="text" placeholder="주차" name="park">
            <input type="text" placeholder="주소" name="address">
            <input type="text" name="tag" placeholder="태그">
        </div>
        <div class="submit">
            <input type="submit" value="올리기">
        </div>
    </form>
{% endblock %}